title: De'Andra's Docs
author: De'Andra B. Taylor
email: taylordb1924@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  What's up? I'm De'Andra and these are my docs. 
  I'm a technical writer *and* a clinical speech-language pathologist. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
